/** English shell copy. Protocol enums and signed payloads remain source values. */
export const shellCopy = {
  controlRoom: "Control room ",
  workspaces: "Workspaces",
  paletteTitle: "Go to workspace",
  paletteDescription: "Navigate to a workspace or a paired server. Operations are reviewed in their workspace.",
  paletteFind: "Find workspace or server",
  pairedServers: "Paired servers",
  paletteEmpty: "No matching workspace or paired server.",
  confirmOperation: "Confirm operation",
  cancel: "Cancel",
  deleteBackup: "This deletes the history record and any retained VPS archive. The canonical Google Drive backup remains stored.",
  resolveRecovery: "Verify Minecraft is online and Host-local RCON readiness is healthy before clearing the recovery gate. The failed backup remains recorded as failed.",
  restartMaintenance: "The Host will run its maintenance warning and readiness workflow before restarting this server.",
  pairTitle: "Pair this browser",
  deviceName: "Device name",
  pairCode: "Six-digit pairing code",
  pairHint: "The code is valid for five minutes and can be used once.",
  pairIntro: "The local operator grants access. This browser keeps the credentials for each paired server.",
  pairExpiryStep: "Enter the one-use code before its five-minute expiry.",
  pairRoleStep: "Open the control room with the role granted locally.",
  pairRole: "Pairing defaults to Observer when no role is supplied. Your server controls every capability.",
  pairWaiting: "Waiting for local approval…",
  pairSubmit: "Open control room",
  pairBack: "Back to server",
  pairPrivacy: "Server identity is signed. Telemetry and file contents are not stored by the relay.",
  pairSelect: "Open a paired server",
  pairFailed: "Pairing failed",
  shortcutsTitle: "Keyboard shortcuts",
  shortcutsDescription: "Navigation only. Two-key shortcuts are ignored while typing or when a dialog is open.",
  showShortcuts: "Show shortcuts",
  bootTitle: "Opening your browser workspace",
  bootDescription: "Restoring paired servers and local preferences.",
  skip: "Skip to workspace",
  openNavigation: "Open navigation",
  selectedServer: "Selected server",
  openPalette: "Open command palette",
  goTo: "Go to",
  openActivity: "Open session activity",
  clientSettings: "Client settings",
  authorityTitle: "Connection authority",
  authorityDetails: "Connection details",
  authorityDescription: "Host owns lifecycle, backups and retained console output. Paper supplies game telemetry and console commands. Paper fallback output is live only.",
  hostState: "Host service state",
  lastReceived: "Last received in browser",
  serviceCaptured: "Service sample captured",
  deviceRole: "Device role",
  boundServer: "Bound server",
  notSupplied: "Not supplied",
  notSelected: "Not selected",
  noServer: "No server selected",
  unknown: "Unknown",
  connected: "Connected",
  disconnected: "Disconnected",
  host: "Host",
  paper: "Paper",
  relay: "Relay",
  console: "Console",
  paperFallback: "Paper fallback",
  unavailable: "Unavailable",
  refresh: "Refresh",
  retry: "Retry connection",
  footer: "Access is granted separately by each server. Operations use the current signed instance.",
  navigation: "Navigation",
  activityTitle: "Session activity",
  activityDescription: "The latest 50 metadata items observed in this tab. No commands, file contents or chat messages are retained here. This is not the server audit log.",
  activityClear: "Clear session activity",
  activityEmpty: "No activity observed in this tab.",
  monitor: "Monitor",
  operate: "Operate",
  manage: "Manage",
  defaultDevice: "My browser",
  pairHeadline: "Connect your browser to your server.",
  pairRun: "Run",
  pairLocally: "locally.",
  confirmBefore: "This operation will run on",
  confirmAfter: "using this device’s local permissions.",
  then: "then",
  cached: " Showing saved history; commands are disabled.",
  backupPhase: "Backup phase",
  serverName: (id: string) => `Server ${id.slice(0, 8)}`,
  loading: (page: string) => `Loading ${page}`,
} as const;
