import test from 'node:test';import assert from 'node:assert/strict';
import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {JSDOM} from 'jsdom';
import {OverviewView} from '../.test-dist/app/overview-view.js';import {emptyControlState} from '../.test-dist/lib/control-state.js';
function state(){const capturedAt=new Date().toISOString();return {...emptyControlState('test-server'),updatedAt:Date.now(),ready:{agents:{paper:true,host:true},server:{instanceKey:'test-instance',minecraftVersion:'26.2',pluginVersion:'5.0.0',hostTargetCompatible:true}},server:{capturedAt,tps:[0],averageTickMillis:0,onlinePlayers:0,maximumPlayers:20},system:{capturedAt,processCpuPercent:22,jvmHeapUsedBytes:0,jvmHeapMaximumBytes:6e9},hostSystem:{capturedAt,hostCpuPercent:35},service:{state:'active',resources:{capturedAt,scope:'MINECRAFT_SERVICE',source:'SYSTEMD_CGROUP',cpuAvailable:true,cpuUnit:'PERCENT_OF_ONE_CORE',cpuPercent:150,memoryAvailable:true,memoryBytes:0}},worlds:[{name:'World',players:0,loadedChunks:0,entities:0}]};}
function render(state,connected=true){return new JSDOM(renderToStaticMarkup(React.createElement(OverviewView,{state,connected,can:()=>false,notice(){},run:async()=>{throw new Error('No operation');}})));}
const reading=(dom,metric)=>dom.window.document.querySelector(`[data-instrument="${metric}"] .instrument-reading strong`).textContent;
test('Overview real zero stays a real reading and all six existing instruments remain',()=>{const dom=render(state());try{assert.equal(dom.window.document.querySelectorAll('[data-instrument]').length,6);for(const [field,value]of [['tps','0.00'],['mspt','0.00 ms'],['players','0'],['heap','0 B'],['serviceCpu','150.0%'],['serviceMemory','0 B']])assert.equal(reading(dom,field),value);assert.match(dom.window.document.querySelector('.overview-details').textContent,/1 world/);}finally{dom.window.close();}});
test('unknown and stale values never borrow zero or unrelated traffic freshness',()=>{const data=state();data.server={capturedAt:new Date(Date.now()-60000).toISOString()};data.system.capturedAt=data.server.capturedAt;data.service.resources.capturedAt=data.server.capturedAt;const dom=render(data);try{for(const field of ['tps','mspt','players','heap','serviceCpu','serviceMemory'])assert.equal(reading(dom,field),'—');}finally{dom.window.close();}});
test('service CPU never borrows Host node CPU or Paper process CPU when cgroup provenance is absent',()=>{const data=state();delete data.service.resources;const dom=render(data);try{assert.equal(reading(dom,'serviceCpu'),'—');assert.doesNotMatch(dom.window.document.querySelector('[data-instrument="serviceCpu"] .instrument-reading').textContent,/35|22/);assert.match(dom.window.document.querySelector('.overview-identity').textContent,/Service uptimeNot supplied/);}finally{dom.window.close();}});
test('Host offline leaves fresh Paper metrics available while service values remain unknown',()=>{const data=state();data.ready.agents.host=false;const dom=render(data);try{assert.equal(reading(dom,'tps'),'0.00');assert.equal(reading(dom,'serviceCpu'),'—');assert.match(dom.window.document.querySelector('.overview-identity').textContent,/Host serviceUnknown/);}finally{dom.window.close();}});
